/* Automatically generated by wasm2c */
#ifndef PLATFORM_H_GENERATED_
#define PLATFORM_H_GENERATED_

#include <stdint.h>

#include "wasm-rt.h"

/* TODO(binji): only use stdint.h types in header */
#ifndef WASM_RT_CORE_TYPES_DEFINED
#define WASM_RT_CORE_TYPES_DEFINED
typedef uint8_t u8;
typedef int8_t s8;
typedef uint16_t u16;
typedef int16_t s16;
typedef uint32_t u32;
typedef int32_t s32;
typedef uint64_t u64;
typedef int64_t s64;
typedef float f32;
typedef double f64;
#endif

#ifdef __cplusplus
extern "C" {
#endif

struct Z_env_instance_t;
extern wasm_rt_memory_t* Z_envZ_memory(struct Z_env_instance_t*);

typedef struct Z_env_instance_t {
  struct Z_env_instance_t* Z_env_instance;
  /* import: 'env' 'memory' */
  wasm_rt_memory_t *Z_envZ_memory;
  u64 w2c_g0;
  u32 w2c_g1;
  u32 w2c_g2;
  u32 w2c_g3;
  u32 w2c_g4;
  u32 w2c_g5;
  u32 w2c_g6;
} Z_env_instance_t;

void Z_env_init_module(void);
void Z_env_instantiate(Z_env_instance_t*, struct Z_env_instance_t*);
void Z_env_free(Z_env_instance_t*);

/* import: 'env' 'cos' */
f32 Z_envZ_cos(struct Z_env_instance_t*, f32);
/* import: 'env' 'exp' */
f32 Z_envZ_exp(struct Z_env_instance_t*, f32);
/* import: 'env' 'logChar' */
void Z_envZ_logChar(struct Z_env_instance_t*, u32);
/* import: 'env' 'pow' */
f32 Z_envZ_pow(struct Z_env_instance_t*, f32, f32);
/* import: 'env' 'sin' */
f32 Z_envZ_sin(struct Z_env_instance_t*, f32);

/* export: 'time' */
f32 Z_envZ_time(Z_env_instance_t*);

/* export: 'isButtonPressed' */
u32 Z_envZ_isButtonPressed(Z_env_instance_t*, u32);

/* export: 'isButtonTriggered' */
u32 Z_envZ_isButtonTriggered(Z_env_instance_t*, u32);

/* export: 'random' */
u32 Z_envZ_random(Z_env_instance_t*);

/* export: 'random64' */
u64 Z_envZ_random64(Z_env_instance_t*);

/* export: 'randomf' */
f32 Z_envZ_randomf(Z_env_instance_t*);

/* export: 'randomSeed' */
void Z_envZ_randomSeed(Z_env_instance_t*, u32);

/* export: 'fmod' */
f32 Z_envZ_fmod(Z_env_instance_t*, f32, f32);

/* export: 'cls' */
void Z_envZ_cls(Z_env_instance_t*, u32);

/* export: 'setPixel' */
void Z_envZ_setPixel(Z_env_instance_t*, u32, u32, u32);

/* export: 'getPixel' */
u32 Z_envZ_getPixel(Z_env_instance_t*, u32, u32);

/* export: 'hline' */
void Z_envZ_hline(Z_env_instance_t*, u32, u32, u32, u32);

/* export: 'rectangle' */
void Z_envZ_rectangle(Z_env_instance_t*, f32, f32, f32, f32, u32);

/* export: 'rectangle_outline' */
void Z_envZ_rectangle_outline(Z_env_instance_t*, f32, f32, f32, f32, u32);

/* export: 'circle' */
void Z_envZ_circle(Z_env_instance_t*, f32, f32, f32, u32);

/* export: 'circle_outline' */
void Z_envZ_circle_outline(Z_env_instance_t*, f32, f32, f32, u32);

/* export: 'line' */
void Z_envZ_line(Z_env_instance_t*, f32, f32, f32, f32, u32);

/* export: 'printChar' */
void Z_envZ_printChar(Z_env_instance_t*, u32);

/* export: 'printString' */
void Z_envZ_printString(Z_env_instance_t*, u32);

/* export: 'printInt' */
void Z_envZ_printInt(Z_env_instance_t*, u32);

/* export: 'setTextColor' */
void Z_envZ_setTextColor(Z_env_instance_t*, u32);

/* export: 'setBackgroundColor' */
void Z_envZ_setBackgroundColor(Z_env_instance_t*, u32);

/* export: 'setCursorPosition' */
void Z_envZ_setCursorPosition(Z_env_instance_t*, u32, u32);

/* export: 'playNote' */
void Z_envZ_playNote(Z_env_instance_t*, u32, u32);

/* export: 'endFrame' */
void Z_envZ_endFrame(Z_env_instance_t*);

/* export: 'sndGes' */
f32 Z_envZ_sndGes(Z_env_instance_t*, u32);

#ifdef __cplusplus
}
#endif

#endif  /* PLATFORM_H_GENERATED_ */
